services:
  buildcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LADYBIRD_GIT_REPO}:/home/ubuntu/ladybird
      - /run/user/${UID:-1000}:/run/user/${UID:-1000}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/${WAYLAND_DISPLAY}
      - /run/user/${UID:-1000}/pulse:/run/user/${UID:-1000}/pulse
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - 'c 226:* rmw' # GPU
    environment:
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/${UID:-1000}
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=wayland
      - XAUTHORITY=${XAUTHORITY}
      - PULSE_SERVER=unix:/run/user/${UID:-1000}/pulse/native
    user: 1000:1000
    group_add:
      - audio
      - sudo
    working_dir: /home/ubuntu/ladybird
    entrypoint: /bin/bash
    tty: true
    stdin_open: true
